#sentry_robot  
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200

  yaw_controller:
    type    : effort_controllers/JointPositionController
    joint   : yaw_joint
    publish_rate: 200
    pid: {p: 30.0, i: 24, d: 2}
